### ISSUE TITLE
the sonata neural voices wont load in nvda.

### ISSUE THREAD

**Issue by AdamRastrand1234** [mush42/sonata-nvda#57]
Hello, I installed piper Sonata neural voices for nvda vertion 3.0, my nvda vertion is 2024.4.1 and went into the voice manager and chose Swedish as The Voice language, and downloaded a voice, I was really excited on the voice because it sounded good, so then I restarted nvda just as usual, and when I would then choose the speech synthesis engine it said "speech synthesis error, could not load sonata neural voices". I am of course very annoyed, but could you please come up with some kind of solution, here is the log file 

Starting NVDA version 2024.4.1 x86
INFO - core.main (09:47:27.861) - MainThread (12384):
Config dir: C:\Users\adamr\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (09:47:27.864) - MainThread (12384):
Loading config: C:\Users\adamr\AppData\Roaming\nvda\nvda.ini
INFO - core.main (09:47:28.344) - MainThread (12384):
Windows version: Windows 11 23H2 (10.0.22631) workstation AMD64
INFO - core.main (09:47:28.344) - MainThread (12384):
Using Python version 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)]
INFO - core.main (09:47:28.344) - MainThread (12384):
Using comtypes version 1.2.0
INFO - core.main (09:47:28.346) - MainThread (12384):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (09:47:28.464) - MainThread (12384):
Loaded synthDriver eloquence
WARNING - mathPres.initialize (09:47:28.469) - MainThread (12384):
MathPlayer 4 not available
INFO - core._setUpWxApp (09:47:28.469) - MainThread (12384):
Using wx version 4.2.2a1 msw (phoenix) wxWidgets 3.2.4 with six version 1.16.0
INFO - brailleInput.initialize (09:47:28.472) - MainThread (12384):
Braille input initialized
INFO - braille.initialize (09:47:28.472) - MainThread (12384):
Using liblouis version 3.31.0
INFO - braille.initialize (09:47:28.472) - MainThread (12384):
Using pySerial version 3.5
INFO - braille.BrailleHandler._setDisplay (09:47:28.474) - MainThread (12384):
Loaded braille display driver 'noBraille', current display has 0 cells.
INFO - core.main (09:47:28.559) - MainThread (12384):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (09:47:28.629) - UIAHandler.UIAHandler.MTAThread (17932):
UIAutomation: IUIAutomation6
INFO - external:sonata_neural_voices.aio._thread_target (09:47:28.882) - piper4nvda_asyncio (7064):
Starting asyncio event loop
INFO - external:piper_neural_voices.aio._thread_target (09:47:29.010) - piper4nvda_asyncio (15968):
Starting asyncio event loop
INFO - external:globalPlugins.openai.GlobalPlugin.__init__ (09:47:30.406) - MainThread (12384):
Open AI initialized. Version: 24.06.29. 3 providers
INFO - core.main (09:47:31.116) - MainThread (12384):
NVDA initialized
INFO - external:synthDrivers.sonata_neural_voices.aio._thread_target (09:47:32.245) - piper4nvda_asyncio (18024):
Starting asyncio event loop
INFO - external:synthDrivers.piper_neural_voices.aio._thread_target (09:47:32.251) - piper4nvda_asyncio (16268):
Starting asyncio event loop
ERROR - external:synthDrivers.piper_neural_voices.SynthDriver.check (09:47:32.251) - MainThread (12384):
Failed to connect to piper GRPC server. Synthesizer will not be available.
Traceback (most recent call last):
  File "C:\Users\adamr\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\__init__.py", line 174, in check
    piper_grpc_server_version = grpc_client.check_grpc_server().result()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.pyc", line 456, in result
  File "concurrent\futures\_base.pyc", line 401, in __get_result
  File "C:\Users\adamr\AppData\Roaming\nvda\addons\piper_neural_voices\synthDrivers\piper_neural_voices\grpc_client\__init__.py", line 109, in check_grpc_server
    return await asyncio.wait_for(
                 ^^^^^^^^^^^^^^^^^
TypeError: wait_for() got an unexpected keyword argument 'loop'
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:32.306) - MainThread (12384):
Appname: nvda
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:32.306) - MainThread (12384):
Appname: nvda
INFO - external:synthDrivers.sonata_neural_voices.SynthDriver.__init__ (09:47:33.194) - MainThread (12384):
Sonata GRPC server running on port 59025
INFO - external:synthDrivers.sonata_neural_voices.SynthDriver.__init__ (09:47:33.194) - MainThread (12384):
Connected to Sonata GRPC server
INFO - external:synthDrivers.sonata_neural_voices.SynthDriver.__init__ (09:47:33.194) - MainThread (12384):
Sonata GRPC server version: 0.2.0
ERROR - synthDriverHandler.setSynth (09:47:34.176) - MainThread (12384):
setSynth failed for sonata_neural_voices
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 483, in setSynth
  File "synthDriverHandler.pyc", line 450, in getSynthInstance
  File "synthDriverHandler.pyc", line 339, in initSettings
  File "synthDriverHandler.pyc", line 363, in loadSettings
  File "C:\Users\adamr\AppData\Roaming\nvda\addons\sonata_neural_voices\synthDrivers\sonata_neural_voices\__init__.py", line 429, in _set_volume
    self._player.setVolume(all=value / 100)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WinmmWavePlayer' object has no attribute 'setVolume'
INFO - synthDriverHandler.setSynth (09:47:34.177) - MainThread (12384):
Falling back to previous synthDriver eloquence
INFO - synthDriverHandler.setSynth (09:47:34.213) - MainThread (12384):
Loaded synthDriver eloquence
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:34.235) - MainThread (12384):
Appname: nvda
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:34.235) - MainThread (12384):
Appname: nvda
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:34.235) - MainThread (12384):
Appname: nvda
INFO - external:globalPlugins.myExplorer.GlobalPlugin.event_nameChange (09:47:34.237) - MainThread (12384):
Appname: nvda

I\m not a programer and i\ve desperatly looked on the internet, but found nothing good as i se it https://github.com/mush42/sonata-nvda/issues/51?utm_source=chatgpt.com https://github.com/mush42/sonata-nvda https://github.com/mush42/sonata-nvda/issues so, I really need piper voices, cause i really want to use them or finetuned models

**Comment by mush42** [comment]
@AdamRastrand1234 a new version is in the making. Will release ASAP.

**Comment by AdamRastrand1234** [comment]
Can you please fix this issue


Den ons 27 nov. 2024 kl 12:18 skrev Musharraf ***@***.***>:
